### ISSUE TITLE
IOexception?

### ISSUE THREAD

**Issue by ManChild420** [RedSpah/HATE#2]
I was able to use the file 10 times but then it kept on coming up with these words: IOException has occured while opening .data.win with a FileStream. Please ensure that the path is correct and try again.

Plz help

**Comment by redspah** [comment]
Post HATE_Log.txt. Should be in the same folder as HATE.

**Comment by ManChild420** [comment]
Time seed - 1461699527
Power - 150
TruePower - 0.5882353
Deleted data.win.
Copied data.win.

This?

**Comment by redspah** [comment]
Sorry for not responding earlier, didn't notice your response.

Yes, this exactly.

**Comment by ManChild420** [comment]
That's okay. Sorry for not seeing what you said early. So is there anything I can do?

**Comment by redspah** [comment]
Copy the whole thing here.
