### ISSUE TITLE
Nintendo switch

### ISSUE THREAD

**Issue by SkylerPixel** [RedSpah/HATE#7]
will/can you add support for the nintendo switch version of undertale using layeredfs, though it is game maker studio 2 you can still open and edit the game.win and theoretically use this with the nintendo switch with [this](https://github.com/fjay69/UndertaleTools/releases/tag/switch) tool and with new developments this could just work as a homebrew app for the nintendo switch that is all automated like the pc version

**Comment by krzys-h** [comment]
If you do want to support GMS2 you'll probably find this useful: https://github.com/krzys-h/UndertaleModTool/wiki/Changes-in-Game-Maker:-Studio-2
